### ISSUE TITLE
Erro ao clicar em "Entre pelo Git"

### ISSUE THREAD

**Issue by lucascc26** [flaviohenriquealmeida/contatooh#2]
Olá Flávio,

Estou lendo livro e criando a aplicação Contatooh.
Após colocar o projeto no GitHub, baixei-o em outro PC e nele não consigo fazer autenticação pelo GitHub.
Quando clico em "Entre pelo Git", recebo o seguinte erro:

ValidationError: Validation failed
   at model.Document.invalidate (D:\dev\Projects\contatoos\node_modules\mongoose\lib\document.js:1023:32)
   at D:\dev\Projects\contatoos\node_modules\mongoose\lib\document.js:972:16
   at validate (D:\dev\Projects\contatoos\node_modules\mongoose\lib\schematype.js:610:7)
   at D:\dev\Projects\contatoos\node_modules\mongoose\lib\schematype.js:627:9
   at Array.forEach (native)
   at SchemaString.SchemaType.doValidate (D:\dev\Projects\contatoos\node_modules\mongoose\lib\schematype.js:614:19)
   at D:\dev\Projects\contatoos\node_modules\mongoose\lib\document.js:970:9
   at doNTCallback0 (node.js:407:9)
   at process._tickCallback (node.js:336:13) 

Tem alguma ideia do que possa ser o problema?
Já tentei reinstalar as dependências do package.json, mas não obtive sucesso.

Desde já, obrigado.

**Comment by flaviohenriquealmeida** [comment]
Vou fechar essa issue e pedir para você postar no fórum sua dúvida. Não é issue do projeto, uma vez que já tenho mais de 500 pessoas que fizeram o deploy. 

Este é nosso fórum: https://www.facebook.com/groups/1534163683531297/

Quando postar, compartilhe o link do seu repositório, assim fica mais fácil para todos ajudarem.
